apiVersion: apps/v1
kind: Deployment

metadata:
  name: spam-prediction-deployment
  labels:
    app: spam-prediction

spec:
  replicas: 3

  selector:
    matchLabels:
      app: spam-prediction

  template:
    metadata:
      labels:
        app: spam-prediction

    spec:
      containers:
        - name: spam-prediction-container
          image: palanikumaran/email-spam-detection-app:latest
          ports:
            - containerPort: 8501
