apiVersion: v1
kind: Pod

metadata:
  name: spam-prediction-pod
  labels:
    project: spam-prediction

spec:
  containers:
    - name: spam-prediction-container
      image: palanikumaran/email-spam-detection-app:latest
      ports:
        - containerPort: 8501

